lib/pages/create_community_page/create_community.dart, lib/pages/create_community_page/create_community_page.dart, lib/pages/search_page/seach_results_widget.dart, lib/util/apis.dart
=> Add UI/UX changes for Search/Create

lib/model/user.dart, lib/pages/profile_page/get_profile.dart, lib/pages/search_page/seach_results_widget.dart
https://user-images.githubusercontent.com/98794408/199649071-15d75c7d-c73e-40b5-a7da-c9dd993b3a3c.mov
=> Fix follow/unfollow displays and button

lib/pages/profile_page/follows_page/followers_list.dart, lib/pages/profile_page/follows_page/following_list.dart, lib/pages/profile_page/follows_page/view_follows.dart, lib/pages/profile_page/get_profile.dart
https://user-images.githubusercontent.com/98794408/199891867-8ca8594f-f811-4e21-8ed9-5cc82df38829.mov
Note: The icon you see on some followers/following is for mutuals
The above screenshots are the changes made today
=> Add displays for following/followers

lib/auth_pages/reset_password.dart, lib/auth_pages/reset_password_code.dart, lib/auth_pages/sign_in.dart, lib/auth_pages/sign_up.dart, lib/main.dart, lib/model/user.dart, lib/pages/community_page/community_page.dart, lib/pages/home_page/home_page.dart, lib/pages/home_page/home_page_content.dart, lib/pages/profile_page/get_profile.dart, lib/pages/profile_page/profile_page.dart, lib/pages/search_page/seach_results_widget.dart, lib/pages/search_page/search_page.dart, lib/util/apis.dart, lib/util/cognito/auth_util.dart, lib/util/cognito/user.dart, lib/util/cognito/user_preferences.dart, lib/util/cognito/user_provider.dart
=> Refresh toke, log cleanup and sign in exception handling

lib/model/community.dart, lib/pages/community_page/community_page.dart, lib/pages/post_widgets/create_post.dart, lib/pages/profile_page/community_list.dart, lib/pages/profile_page/get_profile.dart, lib/pages/search_page/seach_results_widget.dart, lib/util/apis.dart, lib/util/date_formatter.dart
https://user-images.githubusercontent.com/91294146/200220483-f4aa4cab-1669-47e0-8b76-90c72dceaa26.mp4
- Combined createPost and checkin lambda in backend
- computeStreak only called once per community
=> Implement Streaks, Checkins, reactive post creation

lib/auth_pages/sign_up.dart, lib/util/cognito/auth_util.dart
=> Signup - username exists exception

lib/constants/routes.dart, lib/pages/common_widgets/navbar.dart, lib/pages/community_page/community_page.dart, lib/pages/goal_page/goal_page.dart, lib/pages/goal_widgets/create_goal_widget.dart, lib/util/apis.dart
=> Add createGoal api/widget and empty goal page

lib/pages/community_page/community_page.dart, lib/pages/home_page/home_page_content.dart, lib/pages/post_page/post_page.dart, lib/pages/post_widgets/post_widget.dart, lib/pages/profile_page/get_profile.dart, lib/util/apis.dart
https://user-images.githubusercontent.com/91294146/201495205-2aa06431-1405-446b-a0de-5ae5fcd174db.mp4
- TODO: Disable clicking the comment button and routing to another post page when already on post page
=> Reactively delete post from post page

lib/pages/post_page/post_page.dart, lib/pages/post_widgets/post_widget.dart
https://user-images.githubusercontent.com/91294146/201498072-461c5f7e-5d84-4ab9-9af3-e616d734a1b7.mp4
=> Disable comment icon navigation on post page

lib/pages/home_page/home_page_content.dart, lib/util/apis.dart
No video, will do a show n' tell in our meeting
=> Add actual homepage with pagination

android/app/src/main/AndroidManifest.xml, lib/model/post.dart, lib/pages/community_page/community_page.dart, lib/pages/home_page/home_page_content.dart, lib/pages/image_related_widgets/add_image_modal.dart, lib/pages/image_related_widgets/single_image_picker.dart, lib/pages/image_related_widgets/upload_image_widget.dart, lib/pages/post_widgets/create_post.dart, lib/pages/post_widgets/post_widget.dart, lib/pages/profile_page/get_profile.dart, lib/util/apis.dart, lib/util/image_utils/image_premissions_util.dart, lib/util/image_utils/single_image_util.dart, pubspec.lock, pubspec.yaml
=> Add images to posts

lib/pages/community_page/community_page.dart, lib/pages/home_page/home_page_content.dart, lib/pages/post_page/post_page.dart, lib/pages/post_widgets/post_widget.dart, lib/pages/profile_page/get_profile.dart
https://user-images.githubusercontent.com/91294146/201510674-117fb0c8-cd4e-493b-bf8c-e61665da930e.mp4
TODO:
- Fix like button moving when number changes
- Comment number not displayed since no comments are actually being returned, probably fix lambda to just return comment number.
- SIDE NOTE: When taking some sort of action on post page and hitting the back button the action won't be displayed on the previous page. We have to reload the page upon hitting the back button. Wasn't able to figure this out.
=> Make Like button more reactive and rework comment button logic on post page

lib/constants/themeSettings.dart, lib/pages/community_page/community_page.dart, lib/pages/goal_widgets/create_goal_widget.dart, lib/pages/post_widgets/create_post.dart, lib/pages/profile_page/get_profile.dart
https://user-images.githubusercontent.com/91294146/201609909-aca54e48-fdb9-4118-bc7c-7404653f2c6b.mp4
TODO
- There is currently no goal being returned for a user on community page, until then can't add logic to hide create goal
- Need an onSuccess method for creating goal. Both for making it reactive and closing out the dialog (Follow along the comments)
- Cleanup create post and create goal ui a bit
=> Add floating action button to community page

lib/model/goal.dart, lib/pages/community_page/community_page.dart, lib/pages/goal_page/get_goal_page.dart, lib/pages/goal_page/goal_page.dart, lib/pages/goal_widgets/create_goal_widget.dart, lib/pages/goal_widgets/goal_widget.dart, lib/util/apis.dart
=> Add getGoal for Goals and Community, deleteGoal

lib/auth_pages/reset_password.dart, lib/auth_pages/reset_password_code.dart, lib/auth_pages/sign_in.dart, lib/auth_pages/sign_up.dart
- Added CircularProgressIndicator (loading spinner) on all auth pages
- Fixed spelling and removed unnecessary comments
UPDATED:
- loading spinner works in both instances (refer to videos)
https://user-images.githubusercontent.com/91173297/203869023-7aac0c19-ec4a-4fa3-a822-98ecb223b4e3.mov
https://user-images.githubusercontent.com/91173297/203869030-c24e8d69-6203-4e9b-bcef-5c142c4e5462.mov
=> Updated UI/UX for auth pages

lib/pages/common_widgets/sortPosts.dart, lib/pages/community_page.dart, lib/pages/profile_page/profile_page.dart
https://user-images.githubusercontent.com/91294146/203917977-fc0f8935-71f5-4475-84d9-5b6fb190982e.mp4
=> Implement Sorting Posts for Community and Profile Pages

lib/auth_pages/signup_page.dart, test/auth_pages/signup_page_test.dart
=> Create test cases for sign up page

lib/auth_pages/login_page.dart, test/auth_pages/login_page_test.dart
=> Create test cases for login page

lib/pages/common_widgets/sort_posts_widget.dart, test/pages/common_widgets/sort_posts_widget_test.dart
=> Add sortPostWidget unit tests

lib/pages/profile_page/community_list.dart, test/pages/profile_page/community_list_test.dart
97% coverage
fixed last post date
=> Add communityListWidget Unit Tests

lib/inroduction_page/intro_banner.dart, test/inroduction_page/intro_banner_test.dart, test/inroduction_page/intro_page_test.dart
100% for banner and 92% for intro
=> Add intro files unit tests
